apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: version-app-pipeline
description: version app pipeline

serialPipeline:
  stages:
  - targetId: dev

  - targetId: prod
    strategy:
      standard:
        verify: false

    # ✅ THIS is the correct approval config
    deployParameters: {}
    profiles: []
    approvalConfigs:
    - approvalRequired: true

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev environment
gke:
  cluster: projects/project-f0e767ca-e0c1-4dd7-af0/locations/us-central1-a/clusters/demo-cluster

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod environment
gke:
  cluster: projects/project-f0e767ca-e0c1-4dd7-af0/locations/us-central1-a/clusters/demo-cluster