steps:
# 1. Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/version-app:$SHORT_SHA', '.']

# 2. Push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/version-app:$SHORT_SHA']

# 3. Deploy to DEV
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/version-app-dev'
    - 'version-app=gcr.io/$PROJECT_ID/version-app:$SHORT_SHA'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'

# 4. Wait for DEV rollout
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rollout'
    - 'status'
    - 'deployment/version-app-dev'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'

# 5. Deploy to PROD
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/version-app-prod'
    - 'version-app=gcr.io/$PROJECT_ID/version-app:$SHORT_SHA'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'

# 6. Wait for PROD rollout
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'rollout'
    - 'status'
    - 'deployment/version-app-prod'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'

timeout: "900s"

options:
  logging: CLOUD_LOGGING_ONLY