apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: version-app
      env: prod
  template:
    metadata:
      labels:
        app: version-app
        env: prod
    spec:
      nodeSelector:
        env: prod   # 🔥 ensures it runs on prod pool

      containers:
      - name: version-app
        image: gcr.io/project-f0e767ca-e0c1-4dd7-af0/version-app:latest

        ports:
        - containerPort: 3000

        env:
        - name: VERSION