apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: version-app
  template:
    metadata:
      labels:
        app: version-app
    spec:
      containers:
      - name: version-app
        image: gcr.io/project-f0e767ca-e0c1-4dd7-af0/version-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000