apiVersion: v1
kind: Service
metadata:
  name: version-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: version-app
    env: main
  ports:
    - port: 80
      targetPort: 3000